"""
analysis.py

This module provides post-simulation telemetry processing and visualization tools
for the neutral_physics_engine. It interfaces directly with the HDF5 output files
generated by the io.py module.

The Analysis class is designed to evaluate the numerical stability and physical
fidelity of the integration schemes. It provides rapid plotting interfaces for
assessing the conservation of system invariants (total energy, linear momentum,
and angular momentum) as dictated by Noether's theorem, as well as tools for
projecting 3D N-body trajectories onto 2D Cartesian planes.

Dependencies:
    numpy      : Matrix and vector mathematics
    matplotlib : Publication-quality 2D plotting
    h5py       : Interface for reading HDF5 binary data
    pathlib    : Object-oriented filesystem paths
"""

import numpy as np
import matplotlib.pyplot as plt
import h5py
from pathlib import Path


class Analysis:
    """
    Context-managed analyzer for N-body simulation HDF5 telemetry data.

    This class provides a suite of diagnostic plotting methods to evaluate the
    quality of a simulation run. It handles opening and safely closing the
    underlying HDF5 dataset, ensuring memory-efficient reads of large phase-space
    arrays.
    """

    def __init__(self, filename: str | Path):
        """
        Initialize the Analysis context manager.

        Parameters:
        -----------
        filename : str | Path
            The file path to the HDF5 simulation output.
        """
        self.filename = Path(filename)
        self.file = None

    def __enter__(self):
        """
        Enter the runtime context and open the HDF5 file in read-only mode.
        """
        self.file = h5py.File(self.filename, "r")
        return self

    def __exit__(self, exc_type, exc, tb):
        """
        Exit the runtime context, ensuring the HDF5 file handle is safely closed.
        """
        if self.file is not None:
            self.file.close()
            self.file = None
        if exc_type is not None:
            print(f"Analysis error: {exc}")
        return False

    # ====================== METADATA ======================
    def get_metadata(self) -> dict:
        """
        Retrieve all global simulation metadata safely.

        Returns:
        --------
        dict
            A dictionary of key-value pairs representing the simulation's
            initial configuration and parameters (e.g., n_bodies, format version).
        """
        if "metadata" not in self.file:
            return {}
        return {k: v for k, v in self.file["metadata"].attrs.items()}

    def get_integrator_name(self) -> str:
        """
        Retrieve the name of the numerical ODE solver used for the simulation.

        Returns:
        --------
        str
            The integrator name (e.g., "rk4", "velocity_verlet"). Defaults to
            "Unknown" if the metadata is missing.
        """
        meta = self.get_metadata()
        return meta.get("integrator", "Unknown")

    # ====================== PLOTS ======================
    def relative_energy_error(self):
        r"""
        Plot the fractional relative energy error over the simulation duration.

        This is a critical diagnostic for evaluating numerical drift and whether
        the chosen integrator exhibits symplectic behavior. The relative error is
        calculated as:
        $\epsilon_E(t) = \frac{E(t) - E_0}{E_0}$

        where $E_0$ is the total initial mechanical energy of the system.
        """
        total_energy = self.file["energy"]["total"][:]
        time = self.file["time"][:]
        E0 = total_energy[0]
        relative_error = (total_energy - E0) / E0

        fig, ax = plt.subplots()
        ax.plot(time, relative_error)
        ax.set_title(f"Relative Energy Error ({self.get_integrator_name()})")
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Relative Energy Error")
        ax.spines["right"].set_visible(False)
        ax.spines["top"].set_visible(False)
        ax.grid(True, alpha=0.3)
        plt.show()

    def plot_energy_components(self):
        """
        Plot the macroscopic kinetic, potential, and total mechanical energies.

        Generates a stacked three-panel plot to visualize the continuous exchange
        between kinetic and potential energy fields over time.
        """
        fig, axs = plt.subplots(3, 1, figsize=(10, 8))
        integrator = self.get_integrator_name()
        t_final = self.file["time"][-1]

        fig.suptitle(f"Energy Components (T={t_final:.1f}s, {integrator})")

        axs[0].plot(self.file["time"][:], self.file["energy"]["kinetic"][:])
        axs[0].set_title("Total Kinetic Energy")
        axs[0].set_xlabel("Time (s)")
        axs[0].set_ylabel("Energy (J)")
        axs[0].spines["right"].set_visible(False)
        axs[0].spines["top"].set_visible(False)

        axs[1].plot(self.file["time"][:], self.file["energy"]["potential"][:])
        axs[1].set_title("Total Potential Energy")
        axs[1].set_xlabel("Time (s)")
        axs[1].set_ylabel("Energy (J)")
        axs[1].spines["right"].set_visible(False)
        axs[1].spines["top"].set_visible(False)

        axs[2].plot(self.file["time"][:], self.file["energy"]["total"][:])
        axs[2].set_title("Total Energy (Kinetic + Potential)")
        axs[2].set_xlabel("Time (s)")
        axs[2].set_ylabel("Energy (J)")
        axs[2].spines["right"].set_visible(False)
        axs[2].spines["top"].set_visible(False)

        plt.tight_layout()
        plt.show()

    def energy_drift_rate(self):
        r"""
        Calculate the global secular energy drift rate.

        Provides a scalar metric of long-term integration stability, computed as:
        $R_{drift} = \frac{E_f - E_0}{E_0 \cdot T}$

        Returns:
        --------
        float
            The normalized energy drift rate in units of inverse seconds ($s^{-1}$).
        """
        Ef = self.file["energy"]["total"][-1]
        E0 = self.file["energy"]["total"][0]
        T = self.file["time"][-1]
        return (Ef - E0) / (E0 * T)

    def plot_linear_momentum(self):
        """
        Plot the magnitude of the total linear momentum of the system over time.

        Used to verify that the physics engine correctly conserves momentum
        (spatial translation symmetry) during collision resolutions and gravity solves.
        """
        fig, ax = plt.subplots()
        ax.plot(self.file["time"][:], self.file["momentum"]["linear_p"][:])
        ax.set_title(f"Linear Momentum Magnitude (T={self.file['time'][-1]:.1f}s)")
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Linear Momentum (kg·m/s)")
        ax.spines["right"].set_visible(False)
        ax.spines["top"].set_visible(False)
        plt.tight_layout()
        plt.show()

    def plot_angular_momentum(self):
        """
        Plot the magnitude of the total internal angular momentum over time.

        Used to verify that the physics engine correctly conserves angular momentum
        (spatial rotation symmetry). Angular momentum is evaluated relative to the
        system's center of mass.
        """
        fig, ax = plt.subplots()
        ax.plot(self.file["time"][:], self.file["momentum"]["angular_p"][:])
        ax.set_title(f"Angular Momentum Magnitude (T={self.file['time'][-1]:.1f}s)")
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Angular Momentum (kg·m²/s)")
        ax.spines["right"].set_visible(False)
        ax.spines["top"].set_visible(False)
        plt.tight_layout()
        plt.show()

    def plot_projection(self, planes: list, body_index=None):
        """
        Plot orthographic projections of body trajectories onto 2D Cartesian planes.

        Extracts the 3D position history for specified bodies and renders their
        orbital/kinematic tracks. Start positions are marked with a circle ('o'),
        and end positions are marked with a cross ('x').

        Parameters:
        -----------
        planes : list[str]
            A list of strings denoting the desired projection planes. Valid options
            are "xy", "xz", and "yz" (case-insensitive).
        body_index : int | list[int] | tuple[int] | None, optional
            The specific body index (or sequence of indices) to plot. If None,
            trajectories for all bodies in the system are plotted.
        """
        valid_planes = {
            "xy": (0, 1, "X Position (m)", "Y Position (m)"),
            "xz": (0, 2, "X Position (m)", "Z Position (m)"),
            "yz": (1, 2, "Y Position (m)", "Z Position (m)"),
        }

        planes = [
            p.lower().strip() for p in planes if p.lower().strip() in valid_planes
        ]
        if not planes:
            print("No valid planes selected.")
            return

        n = len(planes)
        fig, axs = plt.subplots(1, n, figsize=(10 * n, 8))
        if n == 1:
            axs = [axs]

        fig.suptitle(
            f"Trajectory Projections (T={self.file['time'][-1]:.1f}s)", fontsize=16
        )

        # Convert body_index to list
        if isinstance(body_index, int):
            target_indices = [body_index]
        elif isinstance(body_index, (list, tuple)):
            target_indices = body_index
        else:
            target_indices = None

        # FIXED: Load positions once (n_steps, n_bodies, 3)
        positions = self.file["positions"][:]  # shape: (n_steps, n_bodies, 3)

        for ax, plane in zip(axs, planes):
            idx_h, idx_v, label_h, label_v = valid_planes[plane]

            for i in range(positions.shape[1]):  # loop over bodies
                if target_indices is not None and i not in target_indices:
                    continue

                body_traj = positions[:, i, :]  # (n_steps, 3) for this body

                if len(body_traj) > 0:
                    h_vals = body_traj[:, idx_h]
                    v_vals = body_traj[:, idx_v]

                    (line,) = ax.plot(h_vals, v_vals, label=f"Body {i}")
                    ax.scatter(
                        h_vals[0],
                        v_vals[0],
                        color=line.get_color(),
                        marker="o",
                        s=40,
                        label="_nolegend_",
                    )
                    ax.scatter(
                        h_vals[-1],
                        v_vals[-1],
                        color=line.get_color(),
                        marker="x",
                        s=40,
                        label="_nolegend_",
                    )

                    ax.set_title(f"{plane.upper()} Plane")
                    ax.set_xlabel(label_h)
                    ax.set_ylabel(label_v)
                    ax.legend()

        plt.tight_layout()
        plt.show()
